/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe_management_system;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Home extends javax.swing.JFrame
{
    public String email;
    public String name;
    public String mob_no;
    public Home()
    {
        initComponents();
    }
     public Home(String usremail,String n,String mob)
    {
        initComponents();
        email=usremail;
        name=n;
        mob_no=mob;
        if(!email.equals("admin@gmail.com"))
        {
            btncat.setVisible(false);
            btnviewEditDelete.setVisible(false);
            btnnewProduct.setVisible(false);
            btnverifyUser.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnlogOut = new javax.swing.JButton();
        btnplaceOrder = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btnnewProduct = new javax.swing.JButton();
        btncat = new javax.swing.JButton();
        btnviewEditDelete = new javax.swing.JButton();
        btnverifyUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        btnlogOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnlogOut.setText("LogOut");
        btnlogOut.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnlogOutActionPerformed(evt);
            }
        });

        btnplaceOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnplaceOrder.setText("Place Order");
        btnplaceOrder.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnplaceOrderActionPerformed(evt);
            }
        });

        btnexit.setBackground(new java.awt.Color(255, 51, 0));
        btnexit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnexitActionPerformed(evt);
            }
        });

        btnnewProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnnewProduct.setText("New Product");
        btnnewProduct.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnnewProductActionPerformed(evt);
            }
        });

        btncat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btncat.setText("Manage Category");
        btncat.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btncatActionPerformed(evt);
            }
        });

        btnviewEditDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnviewEditDelete.setText("View,Edit and Delete Product");
        btnviewEditDelete.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnviewEditDeleteActionPerformed(evt);
            }
        });

        btnverifyUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnverifyUser.setText("Verify Users");
        btnverifyUser.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnverifyUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btncat)
                .addGap(66, 66, 66)
                .addComponent(btnnewProduct)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnviewEditDelete)
                        .addGap(76, 76, 76)
                        .addComponent(btnverifyUser)
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnexit)
                        .addGap(80, 80, 80))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnlogOut)
                .addGap(88, 88, 88)
                .addComponent(btnplaceOrder)
                .addGap(369, 369, 369))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnplaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 432, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncat, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnewProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnviewEditDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnverifyUser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnplaceOrderActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnplaceOrderActionPerformed
    {//GEN-HEADEREND:event_btnplaceOrderActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new PlaceOrder(email,name,mob_no).setVisible(true);
    }//GEN-LAST:event_btnplaceOrderActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnexitActionPerformed
    {//GEN-HEADEREND:event_btnexitActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Do ypu really want to exit?","select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnlogOutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnlogOutActionPerformed
    {//GEN-HEADEREND:event_btnlogOutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
    }//GEN-LAST:event_btnlogOutActionPerformed

    private void btncatActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btncatActionPerformed
    {//GEN-HEADEREND:event_btncatActionPerformed
        // TODO add your handling code here:
        new ManageCategory().setVisible(true);
        
    }//GEN-LAST:event_btncatActionPerformed

    private void btnnewProductActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnnewProductActionPerformed
    {//GEN-HEADEREND:event_btnnewProductActionPerformed
        // TODO add your handling code here:
        new AddNewProduct().setVisible(true);
    }//GEN-LAST:event_btnnewProductActionPerformed

    private void btnviewEditDeleteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnviewEditDeleteActionPerformed
    {//GEN-HEADEREND:event_btnviewEditDeleteActionPerformed
        // TODO add your handling code here:
        new ViewEditDelete().setVisible(true);
    }//GEN-LAST:event_btnviewEditDeleteActionPerformed

    private void btnverifyUserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnverifyUserActionPerformed
    {//GEN-HEADEREND:event_btnverifyUserActionPerformed
        // TODO add your handling code here:
        new VerifyUsers().setVisible(true);
    }//GEN-LAST:event_btnverifyUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncat;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnlogOut;
    private javax.swing.JButton btnnewProduct;
    private javax.swing.JButton btnplaceOrder;
    private javax.swing.JButton btnverifyUser;
    private javax.swing.JButton btnviewEditDelete;
    // End of variables declaration//GEN-END:variables
}
